[connections.supabase]
SUPABASE_URL = https://paxolsdymswbzrgadqie.supabase.co
SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBheG9sc2R5bXN3YnpyZ2FkcWllIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NDQwMDU2NiwiZXhwIjoyMDU5OTc2NTY2fQ.2Kt2oGAlo3Ws0I6rJD9A5Pk02Etd_d4idJ15_gXZgl4
